# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911a0d525389b6af1882ea87aa31202d80f62ea2f08b03754046436f835914540dc8ed0747b381dcca045bd9d14a0e24a8085e998c36576e34216eb89651d6aa

test:
  secret_key_base: 0fe5c891fad2b0273ac4402e818ce3a028a7a63f09f58d0582557e8013a4e4aa3bab28679149ad6809430475716977088de9d8653b9fe3af96cdd6a5106fd07b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
